//edited
//document.write('<table width="100%" cellspacing="0" cellpadding="0" border="0"				bordercolor="block">				<tbody>					<tr>						<td valign="top">							<table class="header" cellspacing="0" cellpadding="0" border="0"								bordercolor="block" width="100%" height="100%">								<tbody>									<tr>									</tr>									<tr>										<td>											<h4>												<b><font color="white">Bhartiya Samruddhi Finance														Limited</font></b>											</h4>											<br> <strong><font color="white">Field Reporting													System</font></strong>										</td>										<td width="90"><img src="images/basix-logo.gif" width="75"											height="100" align="middle" /></td>									</tr>								</tbody>							</table>						</td>					</tr>					<tr>						<td valign="top" height="5" align="right" class="nav_head"></td>					</tr>					<tr class="content-area" valign="top">						<td>									<!---------------- Code for FRS theme Atop2.js ends here  ------------------------->');


//document.write('<table width="100%" cellspacing="0" cellpadding="0" border="0"				bordercolor="block">				<tbody>					<tr>						<td valign="top">							<table class="header" cellspacing="0" cellpadding="0" border="0"								bordercolor="block" width="100%" height="100%">								<tbody>									<tr>									</tr>									<tr>										<td>											<h4>												<b><font color="white">Bhartiya Samruddhi Finance														Limited</font></b>											</h4>											<br> <strong><font color="white">Field Reporting													System</font></strong>										</td>			<td align="right" valign="bottom"> <b> <font color="white">  <%=((HttpServletRequest) request).getSession().getAttribute("username").toString() %>  Logged in as <%=((HttpServletRequest) request).getSession().getAttribute("userrole").toString().toUpperCase() %>  </font>  </b>  </td>							<td width="90"><img src="images/basix-logo.gif" width="75"											height="100" align="middle" /></td>									</tr>								</tbody>							</table>						</td>					</tr>					<tr>						<td valign="top" height="5" align="right" class="nav_head"></td>					</tr>					<tr class="content-area" valign="top">						<td>									<!---------------- Code for FRS theme Atop2.js ends here  ------------------------->');

//document.write('<table width="100%" cellspacing="0" cellpadding="0" border="0"				bordercolor="block">				<tbody>					<tr>						<td valign="top">							<table class="header" cellspacing="0" cellpadding="0" border="0"								bordercolor="block" width="100%" height="100%">								<tbody>									<tr>									</tr>									<tr>										<td>											<h4>												<b><font color="white">Bhartiya Samruddhi Finance														Limited</font></b>											</h4>											<br> <strong><font color="white">Field Reporting													System</font></strong>										</td>			<td align="right" valign="bottom"> <b> <font color="white">  BASIX  Logged in as ADMIN  </font>  </b>  </td>		<td align="right" width="10"> </td>					<td width="90"><img src="images/basix-logo.gif" width="75"											height="100" align="middle" /></td>									</tr>								</tbody>							</table>						</td>					</tr>					<tr>						<td valign="top" height="5" align="right" class="nav_head"></td>					</tr>					<tr class="content-area" valign="top">						<td>									<!---------------- Code for FRS theme Atop2.js ends here  ------------------------->');
document.write('<table width="100%" cellspacing="0" cellpadding="0" border="0"				bordercolor="block">				<tbody>					<tr>						<td valign="top">							<table class="header" cellspacing="0" cellpadding="0" border="0"								bordercolor="block" width="100%" height="100%">								<tbody>									<tr>									</tr>									<tr>										<td>											<h4>												<b><font color="white">Bhartiya Samruddhi Finance														Limited</font></b>											</h4>											<br> <strong><font color="white">Field Reporting													System</font></strong>										</td>			<td align="right" valign="bottom">');
if(username_js!="null")document.write('<b>		<font color="white" style="font-size: 11px">        <i>'+username_js+'</i> Logged in from <i>'+unitname_js+'</i> Unit      </font>     </b>');
//if(username_js!="null")document.write('<b> <font color="white"><i>'+username_js+'</i> Logged in from <i>'+unitname_js+'</i> Unit </font>  </b>');
document.write('</td>		<td align="right" width="10"> </td>					<td width="90"><img src="images/basix-logo.gif" width="75"											height="100" align="middle" /></td>									</tr>								</tbody>							</table>						</td>					</tr>					<tr>						<td valign="top" height="5" align="right" class="nav_head"></td>					</tr>					<tr class="content-area" valign="top">						<td>									<!---------------- Code for FRS theme Atop2.js ends here  ------------------------->');



																																							






//document.write('<table width="100%" cellspacing="0" cellpadding="0" border="0"				bordercolor="block">				<tbody>					<tr>						<td valign="top">							<table class="header" cellspacing="0" cellpadding="0" border="0"								bordercolor="block" width="100%" height="100%">								<tbody>									<tr>									</tr>									<tr>										<td>											<h4>												<b><font color="white">Bhartiya Samruddhi Finance														Limited</font></b>											</h4>											<br> <strong><font color="white">Field Reporting													System</font></strong>										</td>										<td width="90"><img src="images/basix-logo.gif" width="80" height="100" align="middle" /> <b><font color="white">  <%=((HttpServletRequest) request).getSession().getAttribute("username").toString() %> </font></b>  <br /><b><font color="white"> (As  <%=((HttpServletRequest) request).getSession().getAttribute("userrole").toString().toUpperCase() %> ) </font></b>  </td>									</tr>								</tbody>							</table>						</td>					</tr>					<tr>						<td valign="top" height="5" align="right" class="nav_head"></td>					</tr>					<tr class="content-area" valign="top">						<td>									<!---------------- Code for FRS theme Atop2.js ends here  ------------------------->');


//For displaying the logged in username and role
//document.write('<table width="100%" cellspacing="0" cellpadding="0" border="0"				bordercolor="block">				<tbody>					<tr>						<td valign="top">							<table class="header" cellspacing="0" cellpadding="0" border="0"								bordercolor="block" width="100%" height="100%">								<tbody>									<tr>									</tr>									<tr>										<td>											<h4>												<b><font color="white">Bhartiya Samruddhi Finance														Limited</font></b>											</h4>											<br> <strong><font color="white">Field Reporting													System</font></strong>										</td>										<td width="90"><img src="images/basix-logo.gif" width="75"											height="100" align="middle" /></td> <td width="200"> <b><font color="white">User Name : <%=((HttpServletRequest) request).getSession().getAttribute("username").toString() %> </font></b> <br/> <br/> <br/> <b><font color="white">Logged in as : <%=((HttpServletRequest) request).getSession().getAttribute("userrole").toString().toUpperCase() %> </font></b> </td>									</tr>								</tbody>							</table>						</td>					</tr>					<tr>						<td valign="top" height="5" align="right" class="nav_head"></td>					</tr>					<tr class="content-area" valign="top">						<td>									<!---------------- Code for FRS theme Atop2.js ends here  ------------------------->');
